apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 3
  template:
    spec:
      initContainers:
      
        - name: migrations
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Test
            - name: VAULT_ADDR
              value: http://vault.vault:8200
            - name: VAULT_ROLE
              value: backend-production
            - name: VAULT_MOUNT
              value: production
      
      containers:
      
        - name: service-a-api
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 200m
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Test
            - name: VAULT_ADDR
              value: http://vault.vault:8200
            - name: VAULT_ROLE
              value: backend-production
            - name: VAULT_MOUNT
              value: production
---